openapi: 3.0.1
info:
  title: "TestPHP API"
  description: "RESTful api для авторизации, регистрации, профиля и новостей"
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: remezovmd@gmail.com
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: User
    description: API для регистрации и авторизации
  - name: Profile
    description: API для профиля
  - name: Articles
    description: API для новостей
paths:
  "/api/articles/":
    get:
      tags:
        - Articles
      summary: Получить все новости
      operationId: ArticlesGet
      description: Возвращает новости постранично
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Articles
                type: object
                properties:
                  current_page:
                    type: integer
                    description: Текущая страница
                  data:
                    type: object
                    description: Данные (Id, Заголовок, Сокращенный текст, Полный текст, Ссылка на фото, Время изменения)
                    properties:
                      id:
                        type: integer
                      title:
                        type: string
                      abbrText:
                        type: string
                      fullText:
                        type: string
                      photo:
                        type: string
                      updated_at:
                        type: string
                  first_page_url:
                    type: string
                    description: Ссылка на первую страницу
                  from:
                    type: integer
                    description: Номер первого элемента на странице
                  last_page:
                    type: integer
                    description: Номер последней страницы
                  last_page_url:
                    type: string
                    description: Ссылка на последнюю страницу
                  next_page_url:
                    type: string
                    description: Ссылка на следующую страницу (если текущая страница последняя, значение будет null)
                  path:
                    type: string
                    description: Базовый путь
                  per_page:
                    type: integer
                    description: Количество элементов на странице
                  prev_page_url:
                    type: string
                    description: Ссылка на предыдущую страницу ()если текущая страница первая, значение будет null)
                  to:
                    type: integer
                    description: Номер последенего элемента на странице
                  total:
                    type: integer
                    description: Общее кКоличество элементов
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string

    post:
      tags:
        - Articles
      summary: Добавить новость
      operationId: ArticleCreate
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                title:
                  type: string
                  description: Обновленный заголовок новости
                abbrText:
                  type: string
                  description: Сокращенный текст
                fullText:
                  type: string
                  description: Полный текст
                photo:
                  type: string
                  description: file to upload
                  format: binary
      responses:
        201:
          description: created
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string

  "/api/articles/{id}":
    get:
      tags:
        - Articles
      summary: Получить новость по ID
      operationId: ArticleGet
      parameters:
        - name: id
          in: path
          description: ID новости которую нужно изменить
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Article
                type: object
                properties:
                  title:
                    type: string
                    description: Заголовок
                  abbrText:
                    type: string
                    description: Сокращенный текст
                  fullText:
                    type: string
                    description: Полный текст
                  photo:
                    type: string
                    description: Ссылка на картинку
                  created_at:
                    type: string
                    description: Дата создания
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
    
    post:
      tags:
        - Articles
      summary: Изменить новость по ID
      operationId: ArticleUpdate
      parameters:
        - name: id
          in: path
          description: ID новости которую нужно изменить
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                title:
                  type: string
                  description: Обновленный заголовок новости
                abbrText:
                  type: string
                  description: Сокращенный текст
                fullText:
                  type: string
                  description: Полный текст
                photo:
                  type: string
                  description: file to upload
                  format: binary
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string

    delete:
      tags:
        - Articles
      summary: Удалить новость по ID
      operationId: ArticleDelete
      parameters:
        - name: id
          in: path
          description: ID новости которую нужно удалить
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string

  "/api/profile/":
    get:
      tags:
        - Profile
      summary: Получить данные профиля текущего пользователя
      operationId: ProfileGet
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Profile
                type: object
                properties:
                  name:
                    type: string
                    description: ФИО пользователя
                  email:
                    type: string
                    description: email пользователя
                  DOB:
                    type: string
                    description: Дата рождения пользователя
                  photo:
                    type: string
                    description: Путь к фотографии на сервере
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
    post:
      tags:
        - Profile
      summary: Изменить профиль текущего пользователя
      operationId: ProfileUpdate
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                name:
                  type: string
                  description: ФИО пользователя
                email:
                  type: string
                  description: email пользователя
                DOB:
                  type: string
                  description: Дата рождения пользователя (в формате ГГГГ-ММ-ДД)
                photo:
                  type: string
                  description: Файл с фотографией
                  format: binary
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string

  "/api/register/":
    post:
      tags:
        - User
      summary: Регистрация
      operationId: UserRegister
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        200:
          description: Successful response
        422:
          description: Validation error

  "/api/login/":
    post:
      tags:
        - User
      summary: Авторизация
      operationId: UserLogin
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                title: Token
                type: object
                properties:
                  token_type:
                    type: string
                  token:
                    type: string
                  expires_at:
                    type: string
          
        422:
          description: Unauthorized

  "/api/logout/":
    post:
      tags:
        - User
      summary: Выход
      operationId: UserLogout
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  mesage:
                    type: string